# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x08messages\" \n\rAppendRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0e\x41ppendResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x17\n\x15GetAllMessagesRequest\"*\n\x16GetAllMessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2\x9c\x01\n\x08Messages\x12;\n\x06\x41ppend\x12\x17.messages.AppendRequest\x1a\x18.messages.AppendResponse\x12S\n\x0eGetAllMessages\x12\x1f.messages.GetAllMessagesRequest\x1a .messages.GetAllMessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPENDREQUEST']._serialized_start=28
  _globals['_APPENDREQUEST']._serialized_end=60
  _globals['_APPENDRESPONSE']._serialized_start=62
  _globals['_APPENDRESPONSE']._serialized_end=94
  _globals['_GETALLMESSAGESREQUEST']._serialized_start=96
  _globals['_GETALLMESSAGESREQUEST']._serialized_end=119
  _globals['_GETALLMESSAGESRESPONSE']._serialized_start=121
  _globals['_GETALLMESSAGESRESPONSE']._serialized_end=163
  _globals['_MESSAGES']._serialized_start=166
  _globals['_MESSAGES']._serialized_end=322
# @@protoc_insertion_point(module_scope)
